services:

  # ==========================================
  # POSTGRESQL
  # ==========================================
  postgres:
    image: postgres:16
    container_name: datapulse-postgres

    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow -d mlflow"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - datapulse-network


  # ==========================================
  # MLFLOW
  # ==========================================
  mlflow:
    image: python:3.11-slim
    container_name: datapulse-mlflow

    depends_on:
      postgres:
        condition: service_healthy

    working_dir: /mlflow

    command: >
      sh -c '
      pip install --no-cache-dir mlflow psycopg2-binary &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --workers 1
      --allowed-hosts "*"
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      --default-artifact-root /mlflow/mlruns
      '

    ports:
      - "5000:5000"

    volumes:
      - ./mlruns:/mlflow/mlruns

    networks:
      - datapulse-network


  # ==========================================
  # FASTAPI
  # ==========================================
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: datapulse-fastapi

    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started

    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow

    ports:
      - "8000:8000"

    volumes:
      - ./src:/app/src

    networks:
      - datapulse-network


# ==========================================
# VOLUMES
# ==========================================
volumes:
  postgres_data:


# ==========================================
# NETWORK
# ==========================================
networks:
  datapulse-network:
    driver: bridge