name: MLOPS DATAPULSE - Docker Compose CI/CD

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]


jobs:

  # =========================================================
  # CI
  # =========================================================

  docker-compose-test:

    runs-on: ubuntu-latest

    steps:

      # -------------------------------------------------------
      # 1. CHECKOUT
      # -------------------------------------------------------

      - name: Checkout code
        uses: actions/checkout@v4


      # -------------------------------------------------------
      # 2. DOCKER BUILDX
      # -------------------------------------------------------

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # -------------------------------------------------------
      # 3. VALIDATE COMPOSE
      # -------------------------------------------------------

      - name: Validate Docker Compose
        run: |
          docker compose config


      # -------------------------------------------------------
      # 4. BUILD
      # -------------------------------------------------------

      - name: Build Docker Compose services
        run: |
          docker compose build


      # -------------------------------------------------------
      # 5. START
      # -------------------------------------------------------

      - name: Start Docker Compose
        run: |
          docker compose up -d


      # -------------------------------------------------------
      # 6. CHECK CONTAINERS
      # -------------------------------------------------------

      - name: Check running containers
        run: |
          docker compose ps


      # -------------------------------------------------------
      # 7. WAIT
      # -------------------------------------------------------

      - name: Wait for services
        run: |
          echo "Waiting for services..."
          sleep 15


      # -------------------------------------------------------
      # 8. TEST FASTAPI
      # -------------------------------------------------------

      - name: Test FastAPI
        run: |
          curl --fail http://localhost:8000


      # -------------------------------------------------------
      # 9. LOGS
      # -------------------------------------------------------

      - name: Show Docker Compose logs
        if: always()
        run: |
          docker compose logs --no-color


      # -------------------------------------------------------
      # 10. DOCKER HUB LOGIN
      # -------------------------------------------------------

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # -------------------------------------------------------
      # 11. PUSH IMAGES
      # -------------------------------------------------------

      - name: Push Docker Compose images
        if: github.event_name == 'push'
        run: |
          docker compose push


      # -------------------------------------------------------
      # 12. STOP
      # -------------------------------------------------------

      - name: Stop Docker Compose
        if: always()
        run: |
          docker compose down -v


   # =========================================================
  # CD - DEPLOY AWS EC2
  # =========================================================

  deploy:

    needs: docker-compose-test

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:

      # -------------------------------------------------------
      # 1. DEPLOY VIA SSH
      # -------------------------------------------------------

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.2.2
        with:

          host: ${{ secrets.EC2_HOST }}

          username: ${{ secrets.EC2_USER }}

          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            set -e

            echo "========================================"
            echo "Starting DATAPULSE deployment"
            echo "========================================"

            # -------------------------------------------------
            # CHECK DIRECTORY
            # -------------------------------------------------

            cd /home/${{ secrets.EC2_USER }}/DATAPULSE

            echo "Current directory:"
            pwd

            echo "Updating repository..."

            sudo git fetch origin main
            sudo git reset --hard origin/main

            # -------------------------------------------------
            # DOCKER
            # -------------------------------------------------

            echo "Pulling latest Docker images..."

            sudo docker compose pull

            echo "Stopping old containers..."

            sudo docker compose down

            echo "Starting new containers..."

            sudo docker compose up -d

            # -------------------------------------------------
            # CLEANUP
            # -------------------------------------------------

            echo "Cleaning unused Docker images..."

            sudo docker image prune -f

            # -------------------------------------------------
            # CHECK
            # -------------------------------------------------

            echo "Checking containers..."

            sudo docker compose ps

            echo "========================================"
            echo "Deployment completed"
            echo "========================================"